const ConsonantEnum = {
  GawGai: { value: "ก", name: `ga:w- gai\\` },
  KhawKhai: { value: "ข", name: `kha:w\\/ khai\\` },
  KhawKhuat: { value: "ฃ", name: `kha:w\\/ khu:at\\` },
  KhawKhwai: { value: "ค", name: `kha:w-- khwa:i-` },
  KhawKhon: { value: "ฅ", name: `kha:w\\/ kho:n\\` },
  KhawRaKhang: { value: "ฆ", name: `kha:w-- ra/ khang--` },
  NgawNgu: { value: "ง", name: `nga:w-- ngu:--` },
  JawJan: { value: "จ", name: `ja:w-- ja:n--` },
  ChawChing: { value: "ฉ", name: `cha:w\\/ ching\\` },
  ChawChang: { value: "ช", name: `cha:w-- cha:ng/` },
  SawSo: { value: "ซ", name: `sa:w-- so:/\\` },
  ChawChoe: { value: "ฌ", name: `cha:w-- choe:--` },
  YawYing: { value: "ญ", name: `ya:w-- ying\\/` },
  DawChaDa: { value: "ฎ", name: `da:w-- cha/ da:--` },
  DtawPaDtak: { value: "ฏ", name: `dta:w-- pa\\ dtak\\` },
  ThawThan: { value: "ฐ", name: `tha:w\\/ tha:n\\/` },
  ThawMonTho: { value: "ฑ", name: `tha:w-- mon-- tho:--` },
  ThawPhuThao: { value: "ฒ", name: `tha:w-- phu:/\\ thao/\\` },
  NawNen: { value: "ณ", name: `na:w-- ne:n--` },
  DawDek: { value: "ด", name: `da:w-- dek\\` },
  DtawTao: { value: "ต", name: `dta:w-- tao\\` },
  ThawThung: { value: "ถ", name: `tha:w\\/ thung\\/` },
  ThawThaHan: { value: "ท", name: `tha:w-- tha/ ha:n\\/` },
  ThawThong: { value: "ธ", name: `tha:w-- thong--` },
  NawNu: { value: "น", name: `na:w-- nu:\\/` },
  BawBayMay: { value: "บ", name: `ba:w-- bay-- may/` },
  BpawBpla: { value: "ป", name: `bpa:w-- bpla--` },
  PhawPhueng: { value: "ผ", name: `pha:w\\/ phu:eng/\\` },
  FawFa: { value: "ฝ", name: `fa:w\\/ fa:\\/` },
  PhawPhan: { value: "พ", name: `pha:w-- pha:n--` },
  FawFan: { value: "ฟ", name: `fa:w-- fan--` },
  PhawSamPhao: { value: "ภ", name: `pha:w-- sam\\/ phao--` },
  MawMa: { value: "ม", name: `ma:w-- ma:/` },
  YawYak: { value: "ย", name: `ya:w-- yak/` },
  RawReua: { value: "ร", name: `ra:w-- reu:a--` },
  LawLing: { value: "ล", name: `la:w-- ling--` },
  WawWaen: { value: "ว", name: `wa:w-- wae:n\\/` },
  SawSaLa: { value: "ศ", name: `sa:w\\/ sa:\\/ la:--` },
  SawRueSi: { value: "ษ", name: `sa:w\\/ reu:-- si:\\/` },
  SawSeua: { value: "ส", name: `sa:w\\/ seu:a\\/` },
  HawHip: { value: "ห", name: `ha:w\\/ hi:p\\` },
  LawJuLa: { value: "ฬ", name: `la:w-- ju\\ la:--` },
  AwAng: { value: "อ", name: `a:w-- a:ng\\` },
  HawNokHug: { value: "ฮ", name: `ha:w-- nok/ hu:g/\\` },
} as const;

export const Consonants = {
  ก: ConsonantEnum.GawGai,
  ข: ConsonantEnum.KhawKhai,
  ฃ: ConsonantEnum.KhawKhuat,
  ค: ConsonantEnum.KhawKhwai,
  ฅ: ConsonantEnum.KhawKhon,
  ฆ: ConsonantEnum.KhawRaKhang,
  ง: ConsonantEnum.NgawNgu,
  จ: ConsonantEnum.JawJan,
  ฉ: ConsonantEnum.ChawChing,
  ช: ConsonantEnum.ChawChang,
  ซ: ConsonantEnum.SawSo,
  ฌ: ConsonantEnum.ChawChoe,
  ญ: ConsonantEnum.YawYing,
  ฎ: ConsonantEnum.DawChaDa,
  ฏ: ConsonantEnum.DtawPaDtak,
  ฐ: ConsonantEnum.ThawThan,
  ฑ: ConsonantEnum.ThawMonTho,
  ฒ: ConsonantEnum.ThawPhuThao,
  ณ: ConsonantEnum.NawNen,
  ด: ConsonantEnum.DawDek,
  ต: ConsonantEnum.DtawTao,
  ถ: ConsonantEnum.ThawThung,
  ท: ConsonantEnum.ThawThaHan,
  ธ: ConsonantEnum.ThawThong,
  น: ConsonantEnum.NawNu,
  บ: ConsonantEnum.BawBayMay,
  ป: ConsonantEnum.BpawBpla,
  ผ: ConsonantEnum.PhawPhueng,
  ฝ: ConsonantEnum.FawFa,
  พ: ConsonantEnum.PhawPhan,
  ฟ: ConsonantEnum.FawFan,
  ภ: ConsonantEnum.PhawSamPhao,
  ม: ConsonantEnum.MawMa,
  ย: ConsonantEnum.YawYak,
  ร: ConsonantEnum.RawReua,
  ล: ConsonantEnum.LawLing,
  ว: ConsonantEnum.WawWaen,
  ศ: ConsonantEnum.SawSaLa,
  ษ: ConsonantEnum.SawRueSi,
  ส: ConsonantEnum.SawSeua,
  ห: ConsonantEnum.HawHip,
  ฬ: ConsonantEnum.LawJuLa,
  อ: ConsonantEnum.AwAng,
  ฮ: ConsonantEnum.HawNokHug,
} as const;
