export const VowelLengths = {
  Short: "Short",
  Long: "Long",
} as const;
export type VowelLength = (typeof VowelLengths)[keyof typeof VowelLengths];

export const Vowels = {
  "-ัวะ": { vowelLength: VowelLengths.Short },
  "-ำ": { vowelLength: VowelLengths.Short }, // -am behaves like short (?)
  "-ัว": { vowelLength: VowelLengths.Long },
  "-ั": { vowelLength: VowelLengths.Short },
  "แ-ว": { vowelLength: VowelLengths.Long },
  "เ-ือะ": { vowelLength: VowelLengths.Short },
  "เ-ือ": { vowelLength: VowelLengths.Long },
  "เ-ียะ": { vowelLength: VowelLengths.Short },
  "เ-ีย": { vowelLength: VowelLengths.Long },
  "แ-ะ": { vowelLength: VowelLengths.Short },
  "เ-อะ": { vowelLength: VowelLengths.Short },
  "เ-าะ": { vowelLength: VowelLengths.Short },
  "เ-ิ": { vowelLength: VowelLengths.Short },
  "เ-อ": { vowelLength: VowelLengths.Long },
  "เ-า": { vowelLength: VowelLengths.Long },
  "-ว": { vowelLength: VowelLengths.Long },
  "แ-อ": { vowelLength: VowelLengths.Long },
  "โ-ะ": { vowelLength: VowelLengths.Short },
  "ไ-": { vowelLength: VowelLengths.Long },
  "ใ-": { vowelLength: VowelLengths.Long },
  "โ-": { vowelLength: VowelLengths.Long },
  "แ-็": { vowelLength: VowelLengths.Short },
  "เ-็": { vowelLength: VowelLengths.Short },
  "เ-ะ": { vowelLength: VowelLengths.Short },
  "แ-": { vowelLength: VowelLengths.Long },
  "เ-": { vowelLength: VowelLengths.Long },
  "-ู": { vowelLength: VowelLengths.Long },
  "-ุ": { vowelLength: VowelLengths.Short },
  "-ือ": { vowelLength: VowelLengths.Long },
  "-ื": { vowelLength: VowelLengths.Long },
  "-ึอ": { vowelLength: VowelLengths.Short },
  "-อ": { vowelLength: VowelLengths.Long },
  "-ึ": { vowelLength: VowelLengths.Short },
  "-ิ": { vowelLength: VowelLengths.Short },
  "-ี": { vowelLength: VowelLengths.Long },
  "-ะ": { vowelLength: VowelLengths.Short },
  "-า": { vowelLength: VowelLengths.Long },
  "-": { vowelLength: VowelLengths.Long },
};
